TYPE=VIEW
query=select `db_crud`.`tbl_nilai`.`id_nilai` AS `id_nilai`,`db_crud`.`tbl_nilai`.`ta` AS `ta`,`db_crud`.`tbl_nilai`.`semester` AS `semester`,`db_crud`.`tbl_nilai`.`nim` AS `nim`,`db_crud`.`tbl_mahasiswa`.`nama_mhs` AS `nama_mhs`,`db_crud`.`tbl_mahasiswa`.`tempat_lahir` AS `tempat_lahir`,`db_crud`.`tbl_mahasiswa`.`tanggal_lahir` AS `tanggal_lahir`,`db_crud`.`tbl_mahasiswa`.`usia` AS `usia`,`db_crud`.`tbl_mahasiswa`.`jenis_kelamin` AS `jenis_kelamin`,`db_crud`.`tbl_mahasiswa`.`agama` AS `agama`,`db_crud`.`tbl_mahasiswa`.`alamat` AS `alamat`,`db_crud`.`tbl_mahasiswa`.`no_hp` AS `no_hp`,`db_crud`.`tbl_mahasiswa`.`a` AS `a`,`db_crud`.`tbl_mahasiswa`.`b` AS `b`,`db_crud`.`tbl_nilai`.`nidn` AS `nidn`,`db_crud`.`tbl_dosen`.`nama_dosen` AS `nama_dosen`,`db_crud`.`tbl_dosen`.`email` AS `email`,`db_crud`.`tbl_dosen`.`telp` AS `telp`,`db_crud`.`tbl_nilai`.`kode_mtk` AS `kode_mtk`,`db_crud`.`tbl_mata_kuliah`.`nama_mtk` AS `nama_mtk`,`db_crud`.`tbl_mata_kuliah`.`sks` AS `sks`,`db_crud`.`tbl_nilai`.`nilai_akhir` AS `nilai_akhir`,`db_crud`.`tbl_nilai`.`nilai_huruf` AS `nilai_huruf`,`db_crud`.`tbl_nilai`.`bobot_nilai` AS `bobot_nilai`,`db_crud`.`tbl_nilai`.`jumlah` AS `jumlah`,`db_crud`.`tbl_nilai`.`keterangan` AS `keterangan` from `db_crud`.`tbl_nilai` join `db_crud`.`tbl_mahasiswa` join `db_crud`.`tbl_mata_kuliah` join `db_crud`.`tbl_dosen` where `db_crud`.`tbl_nilai`.`nim` = `db_crud`.`tbl_mahasiswa`.`nim` and `db_crud`.`tbl_nilai`.`nidn` = `db_crud`.`tbl_dosen`.`nidn` and `db_crud`.`tbl_nilai`.`kode_mtk` = `db_crud`.`tbl_mata_kuliah`.`kode_mtk`
md5=7c599105dfd12673556a3c2b4d36f739
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001677497850232825
create-version=2
source=SELECT\n`tbl_nilai`.`id_nilai`,\n`tbl_nilai`.`ta`,\n`tbl_nilai`.`semester`,\n`tbl_nilai`.`nim`,\n\n`tbl_mahasiswa`.`nama_mhs`,\n`tbl_mahasiswa`.`tempat_lahir`,\n`tbl_mahasiswa`.`tanggal_lahir`,\n`tbl_mahasiswa`.`usia`,\n`tbl_mahasiswa`.`jenis_kelamin`,\n`tbl_mahasiswa`.`agama`,\n`tbl_mahasiswa`.`alamat`,\n`tbl_mahasiswa`.`no_hp`,\n`tbl_mahasiswa`.`a`,\n`tbl_mahasiswa`.`b`,\n\n`tbl_nilai`.`nidn`,\n\n`tbl_dosen`.`nama_dosen`,\n`tbl_dosen`.`email`,\n`tbl_dosen`.`telp`,\n\n`tbl_nilai`.`kode_mtk`,\n\n`tbl_mata_kuliah`.`nama_mtk`,\n`tbl_mata_kuliah`.`sks`,\n\n`tbl_nilai`.`nilai_akhir`,\n`tbl_nilai`.`nilai_huruf`,\n`tbl_nilai`.`bobot_nilai`,\n`tbl_nilai`.`jumlah`,\n`tbl_nilai`.`keterangan`\n\nFROM\n`tbl_nilai`,`tbl_mahasiswa`,`tbl_mata_kuliah`,`tbl_dosen`\n\nWHERE\n`tbl_nilai`.`nim` = `tbl_mahasiswa`.`nim` AND\n`tbl_nilai`.`nidn` = `tbl_dosen`.`nidn` AND\n`tbl_nilai`.`kode_mtk` = `tbl_mata_kuliah`.`kode_mtk`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `db_crud`.`tbl_nilai`.`id_nilai` AS `id_nilai`,`db_crud`.`tbl_nilai`.`ta` AS `ta`,`db_crud`.`tbl_nilai`.`semester` AS `semester`,`db_crud`.`tbl_nilai`.`nim` AS `nim`,`db_crud`.`tbl_mahasiswa`.`nama_mhs` AS `nama_mhs`,`db_crud`.`tbl_mahasiswa`.`tempat_lahir` AS `tempat_lahir`,`db_crud`.`tbl_mahasiswa`.`tanggal_lahir` AS `tanggal_lahir`,`db_crud`.`tbl_mahasiswa`.`usia` AS `usia`,`db_crud`.`tbl_mahasiswa`.`jenis_kelamin` AS `jenis_kelamin`,`db_crud`.`tbl_mahasiswa`.`agama` AS `agama`,`db_crud`.`tbl_mahasiswa`.`alamat` AS `alamat`,`db_crud`.`tbl_mahasiswa`.`no_hp` AS `no_hp`,`db_crud`.`tbl_mahasiswa`.`a` AS `a`,`db_crud`.`tbl_mahasiswa`.`b` AS `b`,`db_crud`.`tbl_nilai`.`nidn` AS `nidn`,`db_crud`.`tbl_dosen`.`nama_dosen` AS `nama_dosen`,`db_crud`.`tbl_dosen`.`email` AS `email`,`db_crud`.`tbl_dosen`.`telp` AS `telp`,`db_crud`.`tbl_nilai`.`kode_mtk` AS `kode_mtk`,`db_crud`.`tbl_mata_kuliah`.`nama_mtk` AS `nama_mtk`,`db_crud`.`tbl_mata_kuliah`.`sks` AS `sks`,`db_crud`.`tbl_nilai`.`nilai_akhir` AS `nilai_akhir`,`db_crud`.`tbl_nilai`.`nilai_huruf` AS `nilai_huruf`,`db_crud`.`tbl_nilai`.`bobot_nilai` AS `bobot_nilai`,`db_crud`.`tbl_nilai`.`jumlah` AS `jumlah`,`db_crud`.`tbl_nilai`.`keterangan` AS `keterangan` from `db_crud`.`tbl_nilai` join `db_crud`.`tbl_mahasiswa` join `db_crud`.`tbl_mata_kuliah` join `db_crud`.`tbl_dosen` where `db_crud`.`tbl_nilai`.`nim` = `db_crud`.`tbl_mahasiswa`.`nim` and `db_crud`.`tbl_nilai`.`nidn` = `db_crud`.`tbl_dosen`.`nidn` and `db_crud`.`tbl_nilai`.`kode_mtk` = `db_crud`.`tbl_mata_kuliah`.`kode_mtk`
mariadb-version=100427
